# Generated by Django 5.0.1 on 2024-06-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_likes_author_alter_likes_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
